---
# pipeline.yml
resources:
  - name: myapp-test-repo
    type: git
    source:
      uri: ((git.myapp_test.uri))
      branch: ((git.myapp_test.branch))
  - name: parameters
    type: git
    source:
      uri: ((git.myapp_test.uri))
      branch: ((git.myapp_test.branch))

jobs:
  - name: show-animal-names
    plan:
      - get: myapp-test-repo
      - get: parameters

      - task: show-animal-names
        input_mapping:
          vars: parameters
        params:
          PARAMS_FILE: vars/myapp-test/pipeline_vars/params.yml
        file: myapp-test-repo/task/parameter_task.yml